steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/ml-demo-418313/alfie:latest
      - -f
      - InsureThat/auto_annie/Dockerfile
      - .
images:
  - gcr.io/ml-demo-418313/alfie:latest
